# Generated by Django 4.2.3 on 2023-07-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('was_included_in_home', models.BooleanField()),
            ],
            options={
                'ordering': ('created',),
                'indexes': [models.Index(fields=['created'], name='toy_toy_created_02acb3_idx')],
            },
        ),
    ]
